<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sm</string>
	</array>
	<key>name</key>
	<string>smc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#source</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directiveStart</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directiveClass</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directiveFsmClass</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directiveHeader</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directiveInclude</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directivePackage</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directiveImport</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directiveDeclare</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directiveAccess</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mapName</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#mapContent</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.smc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>/\*\*/</string>
					<key>name</key>
					<string>comment.block.empty.smc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
			</array>
		</dict>
		<key>comments-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.smc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.smc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.smc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.smc</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.double-slash.smc</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>directiveAccess</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.access.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.access.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%access)(?:\s+)([_A-Za-z][_0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.access.smc</string>
		</dict>
		<key>directiveClass</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.class.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%class)(?:\s+)([_A-Za-z][_0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.class.smc</string>
		</dict>
		<key>directiveDeclare</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declare.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.declare.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%declare)(?:\s+)([_A-Za-z][_0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.declare.smc</string>
		</dict>
		<key>directiveFsmClass</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.fsmclass.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%fsmclass)(?:\s+)([_A-Za-z][_0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.fsmclass.smc</string>
		</dict>
		<key>directiveHeader</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.header.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.header.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%header)(?:\s+)([_A-Za-z][_0-9A-Za-z.]*)</string>
			<key>name</key>
			<string>meta.header.smc</string>
		</dict>
		<key>directiveImport</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.import.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%import)(?:\s+)([_A-Za-z][_.0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.import.smc</string>
		</dict>
		<key>directiveInclude</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.include.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.include.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%include)(?:\s+)([_A-Za-z][_0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.include.smc</string>
		</dict>
		<key>directivePackage</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.package.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.package.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%package)(?:\s+)([_A-Za-z][_.0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.package.smc</string>
		</dict>
		<key>directiveStart</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.start.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.map.smc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.smc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.startstate.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%start)(?:\s+)([_A-Za-z][_0-9A-Za-z]*)(::)([_A-Za-z][_0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.start.smc</string>
		</dict>
		<key>mapContent</key>
		<dict>
			<key>begin</key>
			<string>\%\%</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.map.start.smc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\%\%</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.map.end.smc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.map.smc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stateName</string>
				</dict>
			</array>
		</dict>
		<key>mapName</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.map.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.map.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\%map)(?:\s+)([_A-Za-z][_0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.map.identifier.smc</string>
		</dict>
		<key>popArguments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.transition.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.smc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.transition.smc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>issue on more than one transition parameter</string>
			<key>match</key>
			<string>([_A-Za-z][_0-9A-Za-z]*\s*)(,*)(\s*[_A-Za-z][_0-9A-Za-z]*)*</string>
			<key>name</key>
			<string>meta.pop.arguments.smc</string>
		</dict>
		<key>popTransition</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=pop)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.smc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.smc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.pop.smc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#popArguments</string>
				</dict>
			</array>
		</dict>
		<key>pushMapTransition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.push.begin.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.map.smc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.smc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.state.smc</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.push.end.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=push)(\()(?:\s*)([_A-Za-z][_0-9A-Za-z]*)(::)([_A-Za-z][_0-9A-Za-z]*)(?:\s*)(\))</string>
			<key>name</key>
			<string>meta.push.smc</string>
		</dict>
		<key>pushStateTransition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.push.begin.smc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.state.smc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.push.end.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=push)(\()(?:\s*)([_A-Za-z][_0-9A-Za-z]*)(?:\s*)(\))</string>
			<key>name</key>
			<string>meta.push.smc</string>
		</dict>
		<key>rawCode</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.actions.begin.smc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.actions.end.smc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.actions.smc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^}]</string>
					<key>name</key>
					<string>keyword.operator.smc</string>
				</dict>
			</array>
		</dict>
		<key>rawGuard</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.guard.begin.smc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.guard.end.smc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.guard.smc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^}]</string>
					<key>name</key>
					<string>keyword.control.guard.smc</string>
				</dict>
			</array>
		</dict>
		<key>source</key>
		<dict>
			<key>begin</key>
			<string>\%\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.source.begin.smc</string>
				</dict>
			</dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.source.smc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\%\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.source.end.smc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.source.smc</string>
		</dict>
		<key>stateEnterExit</key>
		<dict>
			<key>begin</key>
			<string>\b(Entry|\bExit)(?:\s*)(?=\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.entryexit.smc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>name</key>
			<string>meta.state.enterexit.smc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rawCode</string>
				</dict>
			</array>
		</dict>
		<key>stateName</key>
		<dict>
			<key>begin</key>
			<string>[_A-Za-z][_0-9A-Za-z]*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.state.smc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.state.end.smc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.state.identifier.smc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stateEnterExit</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>[_A-Za-z][_0-9A-Za-z]*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.other.transition.smc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\})</string>
					<key>name</key>
					<string>meta.transition.smc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#rawCode</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pushMapTransition</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pushStateTransition</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#popTransition</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#transitionArguments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rawGuard</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(nil|push|pop)</string>
							<key>name</key>
							<string>storage.type.state.keywords.smc</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b([_A-Za-z][_0-9A-Za-z]*)</string>
							<key>name</key>
							<string>storage.type.nextstate.smc</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>transitionArguments</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.transition.begin.smc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.transition.end.smc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.transition.arguments.smc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#transitionParameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#transitionParameterType</string>
				</dict>
			</array>
		</dict>
		<key>transitionParameter</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.transition.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_A-Za-z][_0-9A-Za-z]*)\s*(?=:)</string>
			<key>name</key>
			<string>meta.transition.parameter.smc</string>
		</dict>
		<key>transitionParameterType</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.transition.parametertype.smc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=:)\s*([_A-Za-z][_.0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.transition.parameter.type.smc</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.smc</string>
	<key>uuid</key>
	<string>CF070B36-855A-48FF-B8F0-1DE8893B7C4D</string>
</dict>
</plist>
